import bg1 from '@/assets/img/login/1.jpg'
import bg2 from '@/assets/img/login/2.jpg'
import bg3 from '@/assets/img/login/3.jpg'
import bg4 from '@/assets/img/login/4.jpg'
import bg5 from '@/assets/img/login/5.jpg'
import bg6 from '@/assets/img/login/6.jpg'
import bg7 from '@/assets/img/login/7.jpg'
import bg8 from '@/assets/img/login/8.jpg'
import bg9 from '@/assets/img/login/9.jpg'
import bg10 from '@/assets/img/login/10.jpg'
import bg11 from '@/assets/img/login/11.jpg'
import bg12 from '@/assets/img/login/12.jpg'
import bg13 from '@/assets/img/login/13.jpg'
import bg14 from '@/assets/img/login/14.jpg'
import bg15 from '@/assets/img/login/15.jpg'
import bg16 from '@/assets/img/login/16.jpg'
import bg17 from '@/assets/img/login/17.jpg'
import bg18 from '@/assets/img/login/18.jpg'

export default [bg1, bg2, bg3, bg4, bg5, bg6, bg7, bg8, bg9, bg10, bg11, bg12, bg13, bg14, bg15, bg16, bg17, bg18]
